import serial, struct, time

ser = serial.Serial('/dev/ttyUSB0', 460800, parity=serial.PARITY_NONE, timeout=1)
print(ser.name)
ser.close()
ser.open()
while True:
    print("Write angles:")
    val1 = int(input("Angle 1: "))
    val2 = int(input("Angle 2: "))
    message = struct.pack('hh', val1, val2)
    print("Message to send: ", message)
    byteNum = ser.write(message)
    print(byteNum)
    resp = ser.read_until()
    print(resp)
    resp = ser.read_until()
    print(resp)
    resp = ser.read_until()
    print(resp)
    resp = ser.read_until()
    print(resp)
    resp = ser.read_until()
    print(resp)
    resp = ser.read_until()
    print(resp)
    resp = ser.read_until()
    print(resp)
    resp = ser.read_until()
    print(resp)
    resp = ser.read_until()
    print(resp)
    print("Done")
    ser.reset_input_buffer()
